// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV6ludHzLInGBZ5CDVH3OWnYMO0R8wvf0',
    appId: '1:569282761179:web:4d8a8cf1068c640b3397fe',
    messagingSenderId: '569282761179',
    projectId: 'event-lister-2cf33',
    authDomain: 'event-lister-2cf33.firebaseapp.com',
    storageBucket: 'event-lister-2cf33.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC30Gp8FEljq6ZsERPOaQTdl_e-ZS641Zc',
    appId: '1:569282761179:android:c706d9bb554359183397fe',
    messagingSenderId: '569282761179',
    projectId: 'event-lister-2cf33',
    storageBucket: 'event-lister-2cf33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJV9W6nmQ6aCcKiIZH_3Mpe50lyoy5JBA',
    appId: '1:569282761179:ios:2baa149dce5e6a903397fe',
    messagingSenderId: '569282761179',
    projectId: 'event-lister-2cf33',
    storageBucket: 'event-lister-2cf33.appspot.com',
    iosBundleId: 'com.example.eventlister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJV9W6nmQ6aCcKiIZH_3Mpe50lyoy5JBA',
    appId: '1:569282761179:ios:cb00e27ef3152ef73397fe',
    messagingSenderId: '569282761179',
    projectId: 'event-lister-2cf33',
    storageBucket: 'event-lister-2cf33.appspot.com',
    iosBundleId: 'com.example.eventlister.RunnerTests',
  );
}
